from pathlib import Path
from typing import Any, Generator, List, Protocol


class DataLoader(Protocol):
    def list_files(self, directory: Path) -> List[Path]: ...
    def load_file(self, file: Path) -> dict | None: ...
    def load_all_files_in_dir(self, path: Path) -> Generator[Any, None, None]: ...
